#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

>&2 echo "Migrating the tables"
python /app/manage.py migrate --no-input

>&2 echo "Collecting static files"
python /app/manage.py collectstatic --no-input

>&2 echo "Importing CSV data into Postgres db..."
python /app/manage.py import_csv

# exec python /app/manage.py runserver 0.0.0.0:8000
exec /usr/local/bin/gunicorn inhs.wsgi --bind 0.0.0.0:8000 --chdir=/app