# Generated by Django 5.1.4 on 2025-01-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField()),
                ('kingdom', models.CharField(max_length=255)),
                ('phylum', models.CharField(max_length=255)),
                ('phylum_class', models.CharField(choices=[('Amphibia', 'Amphibia'), ('Reptilia', 'Reptilia')], default='Amphibia', max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('genus', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('state_province', models.CharField(max_length=255)),
                ('decimal_latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('decimal_longitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
            options={
                'db_table': 'species_locations',
            },
        ),
    ]
